# Generated by Django 4.1.2 on 2022-10-15 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_venue_email_address_alter_venue_phone_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="MyClubUser",),
    ]
