# Generated by Django 4.1.2 on 2022-10-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_event_attendees"),
    ]

    operations = [
        migrations.DeleteModel(name="MyClubUser",),
    ]
